### ISSUE TITLE
error to start

### ISSUE THREAD

**Issue by warriorhood** [SBV-Cybersec/onion_check#1]
Hi, after I have installed the app, appear this error to launch:
![errorOnionCheck](https://user-images.githubusercontent.com/62082865/132118548-ce35bdbf-8f0c-425a-ae25-d4cb80d247b0.png)

**Comment by SBV-Cybersec** [comment]
Hi @warriorhood, The script accepts a text file containing onion URLs as input (One URL in a line). You can save the onion URLs of your interest in a text file and provide the file as input. 
Let me know if you face any issues with the same.

**Comment by CyberSoldiers** [comment]
Hi @warriorhood, The script accepts a text file containing onion URLs as input (One URL in a line). You can save the onion URLs of your interest in a text file and provide the file as input.
Let me know if you face any issues with the same.
